import { readStore, writeStore, makeId } from '../utils/store.js';

function validatePayload(body) { return body.title?.trim() && ['low', 'medium', 'high'].includes(body.priority || 'medium') && (!body.dueDate || !Number.isNaN(Date.parse(body.dueDate))); }
export async function listTodos(request, response) {
  const { status, priority, category, search, sort = 'newest' } = request.query;
  const store = await readStore(); let todos = store.todos.filter((todo) => todo.userId === request.user.id);
  if (status === 'completed') todos = todos.filter((todo) => todo.completed); if (status === 'pending') todos = todos.filter((todo) => !todo.completed);
  if (priority && ['low', 'medium', 'high'].includes(priority)) todos = todos.filter((todo) => todo.priority === priority); if (category) todos = todos.filter((todo) => todo.category === category);
  if (search) todos = todos.filter((todo) => `${todo.title} ${todo.description}`.toLowerCase().includes(search.toLowerCase()));
  const priorityOrder = { low: 1, medium: 2, high: 3 }; todos.sort((a, b) => sort === 'oldest' ? a.createdAt - b.createdAt : sort === 'dueDate' ? (a.dueDate || '9999').localeCompare(b.dueDate || '9999') : sort === 'priority' ? priorityOrder[b.priority] - priorityOrder[a.priority] : b.createdAt - a.createdAt); response.json(todos);
}
export async function getTodo(request, response) { const store = await readStore(); const todo = store.todos.find((entry) => entry.id === request.params.id && entry.userId === request.user.id); if (!todo) return response.status(404).json({ message: 'Todo not found' }); response.json(todo); }
export async function createTodo(request, response) { if (!validatePayload(request.body)) return response.status(400).json({ message: 'Title and valid priority are required' }); const store = await readStore(); const todo = { id: makeId(), userId: request.user.id, title: request.body.title.trim(), description: request.body.description || '', completed: Boolean(request.body.completed), priority: request.body.priority || 'medium', category: request.body.category || 'General', dueDate: request.body.dueDate || null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; store.todos.unshift(todo); await writeStore(store); response.status(201).json(todo); }
export async function updateTodo(request, response) { const store = await readStore(); const index = store.todos.findIndex((entry) => entry.id === request.params.id && entry.userId === request.user.id); if (index < 0) return response.status(404).json({ message: 'Todo not found' }); const next = { ...store.todos[index], ...request.body, updatedAt: new Date().toISOString() }; if (!validatePayload(next)) return response.status(400).json({ message: 'Invalid todo data' }); delete next.userId; next.userId = request.user.id; store.todos[index] = next; await writeStore(store); response.json(next); }
export async function deleteTodo(request, response) { const store = await readStore(); const before = store.todos.length; store.todos = store.todos.filter((entry) => !(entry.id === request.params.id && entry.userId === request.user.id)); if (store.todos.length === before) return response.status(404).json({ message: 'Todo not found' }); await writeStore(store); response.status(204).send(); }
